export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const ORDER_CONFIRM = "ORDER_CONFIRM";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";
export const INIT_INGREDIENTS = "INIT_INGREDIENTS";


export const BURGER_ORDER_INIT = "BURGER_ORDER_INIT";
export const BURGER_ORDER_START = "BURGER_ORDER_START";
export const BURGER_ORDER_SUCCESS = "BURGER_ORDER_SUCCESS";
export const BURGER_ORDER_FAIL = "BURGER_ORDER_FAIL";
export const BURGER_ORDER_SENT = "BURGER_ORDER_SENT";

export const ORDERS_FETCH = "ORDERS_FETCH";
export const ORDERS_FETCH_START = "ORDERS_FETCH_START";
export const ORDERS_FETCH_SUCCESS = "ORDERS_FETCH_SUCCESS";
export const ORDERS_FETCH_FAIL = "ORDERS_FETCH_FAIL";

export const CHECK_STATE = "CHECK_STATE";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_START = "AUTH_START";
export const AUTH_FAIL = "AUTH_FAIL";
export const INITIAT_LOGOUT = "INITIAT_LOGOUT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT"
export const AUTH_USER = "AUTH_USER";

